# Generated by Django 5.1.3 on 2025-05-01 13:00

import HealthRecords.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Reference to the securely stored document file.",
                        upload_to=HealthRecords.models.patient_document_path,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True,
                        help_text="Original filename at time of upload.",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, help_text="MIME type of the file.", max_length=100
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Size of the file in bytes.", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of the document.",
                        max_length=255,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Document",
                "verbose_name_plural": "Patient Documents",
                "ordering": ["patient", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalHealthcareProvider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("clinic", "Clinic"),
                            ("lab", "Laboratory"),
                            ("pharmacy", "Pharmacy"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="National Provider Identifier or other unique ID",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("fhir", "FHIR"),
                            ("hl7", "HL7"),
                            ("direct", "Direct Protocol"),
                            ("api", "Custom API"),
                            ("other", "Other"),
                        ],
                        default="fhir",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "supported_data_types",
                    models.JSONField(
                        default=list,
                        help_text="Types of data this provider can exchange",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Healthcare Provider",
                "verbose_name_plural": "External Healthcare Providers",
            },
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Hospital / Organization",
                "verbose_name_plural": "Hospitals / Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("specialty", models.CharField(blank=True, max_length=100)),
                (
                    "license_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "doctor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctor Profiles",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="OCRText",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ocr_text",
                        serialize=False,
                        to="HealthRecords.document",
                    ),
                ),
                (
                    "full_text",
                    models.TextField(
                        blank=True,
                        help_text="Full text extracted from the document via OCR.",
                    ),
                ),
            ],
            options={
                "verbose_name": "OCR Extracted Text",
                "verbose_name_plural": "OCR Extracted Texts",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="HealthRecords.hospital",
            ),
        ),
        migrations.CreateModel(
            name="DoctorHospitalAffiliation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the doctor's primary practice location?",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliations",
                        to="HealthRecords.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_affiliations",
                        to="HealthRecords.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Hospital Affiliation",
                "verbose_name_plural": "Doctor Hospital Affiliations",
                "ordering": ["doctor__user__last_name", "hospital__name"],
                "unique_together": {("doctor", "hospital")},
            },
        ),
        migrations.AddField(
            model_name="doctor",
            name="hospitals",
            field=models.ManyToManyField(
                help_text="Hospitals where this doctor practices.",
                related_name="affiliated_doctors",
                through="HealthRecords.DoctorHospitalAffiliation",
                to="HealthRecords.hospital",
            ),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Patient's legal first name.", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_index=True,
                        help_text="Patient's legal last name.",
                        max_length=100,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(help_text="Patient's date of birth."),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("undisclosed", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number.",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Patient's primary address.",
                        max_length=255,
                    ),
                ),
                (
                    "global_identifier",
                    models.CharField(
                        db_index=True,
                        help_text="Unique global identifier for the patient (e.g., system-wide MRN).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True, help_text="Patient's blood group", max_length=10
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in cm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="Known allergies"),
                ),
                (
                    "chronic_conditions",
                    models.TextField(
                        blank=True, help_text="Chronic medical conditions"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("insurance_provider", models.CharField(blank=True, max_length=100)),
                ("insurance_id", models.CharField(blank=True, max_length=100)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="patient_photos/"
                    ),
                ),
                (
                    "external_provider_ids",
                    models.JSONField(
                        default=dict,
                        help_text="Map of external provider IDs for this patient",
                    ),
                ),
                (
                    "data_sharing_preferences",
                    models.JSONField(
                        default=dict, help_text="Patient's preferences for data sharing"
                    ),
                ),
                (
                    "last_record_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time records were synced with external providers",
                        null=True,
                    ),
                ),
                (
                    "primary_hospital",
                    models.ForeignKey(
                        help_text="Patient's primary associated hospital/clinic (for tenancy context).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_patients",
                        to="HealthRecords.hospital",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patient Profiles",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "test_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the lab test performed.",
                        max_length=255,
                    ),
                ),
                (
                    "result_value",
                    models.CharField(
                        help_text="The quantitative or qualitative result.",
                        max_length=255,
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        blank=True,
                        help_text="Units of measurement for the result.",
                        max_length=50,
                    ),
                ),
                (
                    "reference_range",
                    models.CharField(
                        blank=True,
                        help_text="Normal reference range for the test.",
                        max_length=100,
                    ),
                ),
                (
                    "result_date",
                    models.DateTimeField(
                        help_text="Date and time the result was recorded/reported."
                    ),
                ),
                (
                    "lab_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from the lab or interpreting physician.",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_results",
                        to="HealthRecords.hospital",
                    ),
                ),
                (
                    "ordering_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordered_lab_results",
                        to="HealthRecords.doctor",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_results_extracted",
                        to="HealthRecords.document",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="HealthRecords.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Result",
                "verbose_name_plural": "Lab Results",
                "ordering": ["patient", "-result_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthDataExchange",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound"),
                            ("outbound", "Outbound"),
                            ("bidirectional", "Bidirectional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("demographics", "Demographics"),
                            ("medications", "Medications"),
                            ("conditions", "Conditions"),
                            ("allergies", "Allergies"),
                            ("lab_results", "Lab Results"),
                            ("imaging", "Imaging"),
                            ("procedures", "Procedures"),
                            ("immunizations", "Immunizations"),
                            ("full_record", "Full Health Record"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partially Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("exchange_date", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "exchange_reference",
                    models.CharField(
                        blank=True,
                        help_text="External reference number",
                        max_length=255,
                    ),
                ),
                (
                    "external_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exchanges",
                        to="HealthRecords.externalhealthcareprovider",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exchanges",
                        to="HealthRecords.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Data Exchange",
                "verbose_name_plural": "Health Data Exchanges",
                "ordering": ["-exchange_date"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyAccessLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        help_text="Reason provided for requiring emergency access."
                    ),
                ),
                (
                    "access_granted",
                    models.BooleanField(
                        default=False,
                        help_text="Was emergency access ultimately granted?",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when access was granted.",
                        null=True,
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_access_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requesting_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emergency_access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_access_logs",
                        to="HealthRecords.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_access_logs",
                        to="HealthRecords.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Access Log",
                "verbose_name_plural": "Emergency Access Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="HealthRecords.patient",
            ),
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "diagnosis_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Standardized diagnosis code (e.g., ICD-10).",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the diagnosis."),
                ),
                (
                    "diagnosis_date",
                    models.DateTimeField(
                        help_text="Date and time the diagnosis was made or recorded."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Is this considered an active/ongoing diagnosis?",
                    ),
                ),
                (
                    "diagnosing_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="made_diagnoses",
                        to="HealthRecords.doctor",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnoses_extracted",
                        to="HealthRecords.document",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnoses",
                        to="HealthRecords.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="HealthRecords.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnosis",
                "verbose_name_plural": "Diagnoses",
                "ordering": ["patient", "-diagnosis_date"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(help_text="Date of the appointment"),
                ),
                (
                    "appointment_time",
                    models.TimeField(help_text="Time of the appointment"),
                ),
                (
                    "duration",
                    models.IntegerField(default=30, help_text="Duration in minutes"),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular Checkup"),
                            ("followup", "Follow-up"),
                            ("specialist", "Specialist Consultation"),
                            ("emergency", "Emergency"),
                        ],
                        default="regular",
                        max_length=50,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the appointment"
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(blank=True, help_text="Patient's symptoms"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, help_text="Reason for cancellation if applicable"
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the appointment"
                    ),
                ),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments",
                        to="HealthRecords.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="HealthRecords.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="HealthRecords.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-appointment_date", "-appointment_time"],
            },
        ),
        migrations.CreateModel(
            name="PatientConsent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("read", "Read Only"),
                            ("write", "Read/Write"),
                            ("full", "Full Access"),
                            ("none", "No Access"),
                        ],
                        default="read",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Date consent becomes active.", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date consent expires (optional).",
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when consent was revoked.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the consent is currently active (not revoked and within date range).",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who granted the consent (usually the patient).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grantee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents_given",
                        to="HealthRecords.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Consent",
                "verbose_name_plural": "Patient Consents",
                "ordering": ["patient", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientDataConsent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sharing_level",
                    models.CharField(
                        choices=[
                            ("none", "No Sharing"),
                            ("basic", "Basic Information"),
                            ("summary", "Clinical Summary"),
                            ("full", "Full Record"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("consent_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "specific_consents",
                    models.JSONField(
                        default=list,
                        help_text="Specific data types consented for sharing",
                    ),
                ),
                ("revocation_date", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_document",
                    models.FileField(
                        blank=True, null=True, upload_to="consent_documents/"
                    ),
                ),
                (
                    "external_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_consents",
                        to="HealthRecords.externalhealthcareprovider",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sharing_consents",
                        to="HealthRecords.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Data Consent",
                "verbose_name_plural": "Patient Data Consents",
                "ordering": ["-consent_date"],
            },
        ),
        migrations.CreateModel(
            name="PatientIdentifier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hospital_patient_id",
                    models.CharField(
                        db_index=True,
                        help_text="The patient identifier specific to this hospital (e.g., MRN).",
                        max_length=100,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_identifiers",
                        to="HealthRecords.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_identifiers",
                        to="HealthRecords.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Hospital Identifier",
                "verbose_name_plural": "Patient Hospital Identifiers",
                "ordering": ["patient", "hospital"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(
                        help_text="Name of the prescribed medication", max_length=255
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        help_text="Strength of the medication (e.g., 500mg)",
                        max_length=50,
                    ),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("syrup", "Syrup"),
                            ("injection", "Injection"),
                            ("cream", "Cream"),
                            ("drops", "Drops"),
                            ("inhaler", "Inhaler"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="How often to take (e.g., twice daily)",
                        max_length=100,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="Duration of the prescription", max_length=100
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Total quantity prescribed"),
                ),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("oral", "Oral"),
                            ("topical", "Topical"),
                            ("injection", "Injection"),
                            ("inhale", "Inhale"),
                            ("other", "Other"),
                        ],
                        default="oral",
                        max_length=50,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Detailed instructions for taking the medication"
                    ),
                ),
                (
                    "side_effects",
                    models.TextField(blank=True, help_text="Potential side effects"),
                ),
                (
                    "warnings",
                    models.TextField(
                        blank=True, help_text="Important warnings or contraindications"
                    ),
                ),
                (
                    "refills",
                    models.IntegerField(
                        default=0, help_text="Number of refills allowed"
                    ),
                ),
                ("refills_remaining", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("pharmacy_notes", models.TextField(blank=True)),
                ("is_controlled_substance", models.BooleanField(default=False)),
                ("filled_date", models.DateTimeField(blank=True, null=True)),
                ("last_filled_date", models.DateTimeField(blank=True, null=True)),
                ("cancelled_date", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="HealthRecords.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="HealthRecords.patient",
                    ),
                ),
                (
                    "prescribing_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_prescriptions",
                        to="HealthRecords.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StandardizedHealthRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("fhir_patient", "FHIR Patient Resource"),
                            ("fhir_condition", "FHIR Condition Resource"),
                            ("fhir_medication", "FHIR Medication Resource"),
                            ("fhir_observation", "FHIR Observation Resource"),
                            ("hl7_adt", "HL7 ADT Message"),
                            ("hl7_oru", "HL7 ORU Message"),
                            ("ccda", "C-CDA Document"),
                            ("other", "Other Format"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(help_text="Standardized health record data")),
                (
                    "version",
                    models.CharField(
                        help_text="Version of the standard used", max_length=50
                    ),
                ),
                ("is_validated", models.BooleanField(default=False)),
                (
                    "validation_errors",
                    models.JSONField(
                        blank=True, default=list, help_text="List of validation errors"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="External reference ID from source system",
                        max_length=255,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standardized_records",
                        to="HealthRecords.patient",
                    ),
                ),
                (
                    "source_system",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provided_records",
                        to="HealthRecords.externalhealthcareprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standardized Health Record",
                "verbose_name_plural": "Standardized Health Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("patient", "Patient"),
                            ("doctor", "Doctor"),
                            ("admin", "Hospital Admin"),
                            ("staff", "Staff"),
                            ("lab_technician", "Lab Technician"),
                            ("pharmacy_staff", "Pharmacy Staff"),
                            ("superuser", "Superuser"),
                        ],
                        db_index=True,
                        default="patient",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hospital affiliation for staff roles (Doctor, Admin, etc.)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_members",
                        to="HealthRecords.hospital",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Account",
                "verbose_name_plural": "User Accounts",
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DataMappingConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "local_model",
                    models.CharField(help_text="Name of local model", max_length=100),
                ),
                (
                    "external_model",
                    models.CharField(
                        help_text="Name of external model/resource", max_length=100
                    ),
                ),
                (
                    "mapping_rules",
                    models.JSONField(
                        help_text="Rules for mapping fields between systems"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "external_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_mappings",
                        to="HealthRecords.externalhealthcareprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Mapping Configuration",
                "verbose_name_plural": "Data Mapping Configurations",
                "unique_together": {
                    ("external_provider", "local_model", "external_model")
                },
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("view", "View"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("export", "Export"),
                            ("emergency_access", "Emergency Access"),
                            ("consent_grant", "Consent Grant"),
                            ("consent_revoke", "Consent Revoke"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True,
                        help_text="Model name being affected (e.g., 'Patient').",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "target_pk",
                    models.CharField(
                        blank=True,
                        help_text="Primary key of the affected record (UUID or other ID).",
                        max_length=36,
                        null=True,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="JSON representation of changes made (optional).",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Contextual description of the action."
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log_entries",
                        to="HealthRecords.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="HealthRecor_user_id_246e0c_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="HealthRecor_action_d6f698_idx",
                    ),
                    models.Index(
                        fields=["target_model", "target_pk"],
                        name="HealthRecor_target__7c38b5_idx",
                    ),
                    models.Index(
                        fields=["hospital", "timestamp"],
                        name="HealthRecor_hospita_9a0392_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="HealthRecor_last_na_02c686_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["date_of_birth"], name="HealthRecor_date_of_f45f29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["patient", "result_date"], name="HealthRecor_patient_b50bab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["hospital", "result_date"],
                name="HealthRecor_hospita_0a290e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["patient", "test_name"], name="HealthRecor_patient_95a664_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyaccesslog",
            index=models.Index(
                fields=["patient", "created_at"], name="HealthRecor_patient_3e9862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyaccesslog",
            index=models.Index(
                fields=["requesting_user", "created_at"],
                name="HealthRecor_request_034840_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyaccesslog",
            index=models.Index(
                fields=["hospital", "created_at"], name="HealthRecor_hospita_f7fa69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["patient", "created_at"], name="HealthRecor_patient_a81d38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["hospital", "created_at"], name="HealthRecor_hospita_33c5a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosis",
            index=models.Index(
                fields=["patient", "diagnosis_date"],
                name="HealthRecor_patient_c2973b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosis",
            index=models.Index(
                fields=["hospital", "diagnosis_date"],
                name="HealthRecor_hospita_65d63d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosis",
            index=models.Index(
                fields=["patient", "is_active", "diagnosis_code"],
                name="HealthRecor_patient_ac7fce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_date"],
                name="HealthRecor_patient_da76ad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "appointment_date"],
                name="HealthRecor_doctor__59c320_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["hospital", "appointment_date"],
                name="HealthRecor_hospita_1db6eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "appointment_date"],
                name="HealthRecor_status_70d820_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientconsent",
            index=models.Index(
                fields=["patient", "grantee"], name="HealthRecor_patient_83d73c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientconsent",
            index=models.Index(
                fields=["patient", "is_active", "end_date"],
                name="HealthRecor_patient_0aa922_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="patientdataconsent",
            unique_together={("patient", "external_provider")},
        ),
        migrations.AlterUniqueTogether(
            name="patientidentifier",
            unique_together={("hospital", "hospital_patient_id")},
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "created_at"], name="HealthRecor_patient_adcce5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["hospital", "created_at"], name="HealthRecor_hospita_371b2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["prescribing_doctor", "created_at"],
                name="HealthRecor_prescri_d381cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["status", "created_at"], name="HealthRecor_status_0d3be5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standardizedhealthrecord",
            index=models.Index(
                fields=["patient", "record_type"], name="HealthRecor_patient_6e5e2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="standardizedhealthrecord",
            index=models.Index(
                fields=["source_system", "external_reference"],
                name="HealthRecor_source__97206e_idx",
            ),
        ),
    ]
