# Generated by Django 5.1.3 on 2025-07-03 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "duration",
                    models.IntegerField(default=30, help_text="Duration in minutes"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", help_text="Hex color code", max_length=7
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchedulingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_appointment_duration",
                    models.IntegerField(
                        default=30, help_text="Default duration in minutes"
                    ),
                ),
                (
                    "min_scheduling_notice",
                    models.IntegerField(
                        default=24, help_text="Minimum hours in advance"
                    ),
                ),
                (
                    "max_days_in_advance",
                    models.IntegerField(
                        default=90, help_text="Maximum days in advance"
                    ),
                ),
                (
                    "buffer_between_appointments",
                    models.IntegerField(default=5, help_text="Buffer in minutes"),
                ),
                ("default_start_time", models.TimeField(default="09:00")),
                ("default_end_time", models.TimeField(default="17:00")),
                ("send_confirmation_emails", models.BooleanField(default=True)),
                ("send_reminder_emails", models.BooleanField(default=True)),
                (
                    "reminder_hours",
                    models.IntegerField(
                        default=24, help_text="Hours before appointment"
                    ),
                ),
                ("send_sms_reminders", models.BooleanField(default=False)),
                (
                    "sms_reminder_hours",
                    models.IntegerField(
                        default=2, help_text="Hours before appointment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Scheduling Settings",
                "verbose_name_plural": "Scheduling Settings",
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("is_clinic_holiday", models.BooleanField(default=False)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.clinic",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledAppointment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_telemedicine", models.BooleanField(default=False)),
                ("is_emergency", models.BooleanField(default=False)),
                ("is_walk_in", models.BooleanField(default=False)),
                (
                    "django_appointment_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Reference to django-appointment's Appointment model if used",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduling_info",
                        to="users.appointment",
                    ),
                ),
                (
                    "appointment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scheduling.appointmenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_appointments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-appointment__appointment_date",
                    "appointment__appointment_time",
                ],
            },
        ),
        migrations.CreateModel(
            name="AppointmentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("break_start_time", models.TimeField(blank=True, null=True)),
                ("break_end_time", models.TimeField(blank=True, null=True)),
                (
                    "appointment_duration",
                    models.IntegerField(default=15, help_text="Duration in minutes"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.clinic"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="users.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("doctor", "clinic", "day_of_week")},
            },
        ),
    ]
