# Generated by Django 5.1.3 on 2025-05-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledappointment",
            name="appointment_type_id",
            field=models.IntegerField(
                blank=True,
                help_text="Reference to django-appointment's AppointmentType model",
                null=True,
            ),
        ),
    ]
