# Generated by Django 5.1.3 on 2024-12-15 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "fix_doctor_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="doctor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="verification_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="consultation_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="license_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="medical_council",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
