# Generated by Django 5.1.3 on 2025-05-04 20:25

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    Appointment = apps.get_model('users', 'Appointment')
    for row in Appointment.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Add UUID field with null=True first
        migrations.AddField(
            model_name='appointment',
            name='uuid',
            field=models.UUIDField(null=True, editable=False),
        ),
        
        # Generate UUIDs for existing records
        migrations.RunPython(gen_uuid),
        
        # Make UUID field non-nullable
        migrations.AlterField(
            model_name='appointment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        
        # Remove the old AutoField primary key
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        
        # Make UUID field the new primary key
        migrations.RenameField(
            model_name='appointment',
            old_name='uuid',
            new_name='id',
        ),
        
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False),
        ),
    ] 