# Generated by Django 5.1.3 on 2024-11-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(default="DEFAULT"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="license_number",
            field=models.CharField(default="DEFAULT", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="medical_degree",
            field=models.CharField(default="MBBS", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=15),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pincode",
            field=models.CharField(default="000000", max_length=10),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="state_council",
            field=models.CharField(default="DEFAULT", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="title",
            field=models.CharField(default="Dr", max_length=10),
        ),
    ]
