# Generated by Django 5.1.3 on 2025-07-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_appointment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentslot",
            name="appointment",
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name="PrescriptionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for easy identification",
                        max_length=200,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Structured prescription data including medicines, diagnosis, etc."
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False, help_text="Mark as favorite for quick access"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this template has been used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_templates",
                        to="users.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_favorite", "-usage_count", "-updated_at"],
                "unique_together": {("doctor", "name")},
            },
        ),
    ]
