# Generated by Django 5.1.3 on 2025-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_doctor_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="doctor",
            name="doctor_license_idx",
        ),
        migrations.RemoveIndex(
            model_name="doctor",
            name="doctor_clinic_idx",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="experience",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="qualification",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name="doctor",
            table="users_doctor",
        ),
    ]
