# Generated by Django 5.1.3 on 2025-02-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_doctor_doctor_license_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="opening_hours",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="specializations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clinic",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
