# Generated by Django 5.1.3 on 2025-07-14 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_appointmentslot_appointment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prescription",
            options={"ordering": ["-created_at"]},
        ),
    ]
