# Generated by Django 5.1.3 on 2024-12-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_appointment_created_at_appointment_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_category", models.CharField(max_length=255)),
                ("product_name", models.CharField(max_length=255)),
                ("salt_composition", models.CharField(max_length=255)),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product_manufactured", models.CharField(max_length=255)),
                ("medicine_desc", models.TextField()),
                ("side_effects", models.TextField()),
                ("drug_interactions", models.JSONField()),
            ],
        ),
    ]
