# Generated by Django 5.1.3 on 2024-12-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_drug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="frequency",
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="duration_unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
