# Generated by Django 5.1.3 on 2024-11-25 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userprofile_first_name_userprofile_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="middle_name",
        ),
    ]
