# Generated by Django 5.1.3 on 2024-12-18 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_prescriptionitem_frequency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescription",
            old_name="notes",
            new_name="advice",
        ),
        migrations.AddField(
            model_name="prescription",
            name="chief_complaints",
            field=models.TextField(default=None, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="clinical_findings",
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PatientVitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="users.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
