# Generated by Django 5.1.3 on 2024-11-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_userprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="year_of_registration",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
