# Generated by Django 5.1.3 on 2025-03-02 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_lab_labstaff_labtechnician_labtest"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtest",
            name="lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.lab",
            ),
        ),
    ]
