# Generated by Django 5.1.3 on 2024-12-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_rename_notes_prescription_advice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientvitals",
            name="heart_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="patientvitals",
            name="oxygen_saturation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="patientvitals",
            name="temparature",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="advice",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
