# Generated by Django 5.1.3 on 2025-03-06 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_labtest_lab"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drug",
            name="drug_interactions",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="medicine_desc",
        ),
        migrations.RemoveField(
            model_name="drug",
            name="side_effects",
        ),
    ]
