# Generated by Django 5.1.3 on 2024-11-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_userprofile_year_of_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="clinic_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
