# Generated by Django 5.1.3 on 2024-12-18 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_patientvitals_heart_rate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientvitals",
            old_name="temparature",
            new_name="temperature",
        ),
    ]
