# Generated by Django 5.1.3 on 2024-11-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_userprofile_clinic_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("pincode", models.CharField(max_length=10)),
            ],
        ),
    ]
