# Generated by Django 5.1.3 on 2025-04-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_staff_is_active_staff_joining_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_walk_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="token_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
