# Generated by Django 5.1.3 on 2024-12-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_rename_temparature_patientvitals_temperature"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="vitals",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescription",
                to="users.patientvitals",
            ),
        ),
    ]
