# Generated by Django 5.1.3 on 2025-04-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_staffleave"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="is_clinic_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="is_lab_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="staff_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
