# Generated by Django 5.1.3 on 2025-04-09 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0001_initial"),
        ("users", "0014_staff_is_clinic_admin_staff_is_lab_admin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lab",
            options={
                "ordering": ["name"],
                "verbose_name": "Lab",
                "verbose_name_plural": "Labs",
            },
        ),
        migrations.RemoveField(
            model_name="labtest",
            name="description",
        ),
        migrations.RemoveField(
            model_name="labtest",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="labtest",
            name="lab",
        ),
        migrations.RemoveField(
            model_name="labtest",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="labtest",
            name="technician",
        ),
        migrations.RemoveField(
            model_name="labtest",
            name="test_name",
        ),
        migrations.AddField(
            model_name="lab",
            name="test_definitions",
            field=models.ManyToManyField(
                related_name="inhouse_labs",
                through="labs.LabTestOffering",
                to="labs.testdefinition",
            ),
        ),
        migrations.AddField(
            model_name="labtest",
            name="test_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_tests",
                to="labs.testdefinition",
            ),
        ),
        migrations.CreateModel(
            name="LabRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("registration_number", models.CharField(max_length=100, unique=True)),
                ("gst_number", models.CharField(max_length=15, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kyc_documents",
                    models.FileField(blank=True, null=True, upload_to="lab_kyc/"),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_labs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabTestPrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prescription_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("BOOKED", "Booked"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "preferred_lab_type",
                    models.CharField(
                        choices=[
                            ("INHOUSE", "In-house Lab"),
                            ("EXTERNAL", "External Lab"),
                            ("PATIENT_CHOICE", "Patient Choice"),
                        ],
                        default="PATIENT_CHOICE",
                        max_length=20,
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "external_lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="labs.labprofile",
                    ),
                ),
                (
                    "inhouse_lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="users.lab",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_prescriptions",
                        to="users.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabTestBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("collection_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("SAMPLE_COLLECTED", "Sample Collected"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "collection_type",
                    models.CharField(
                        choices=[
                            ("LAB_VISIT", "Lab Visit"),
                            ("HOME_COLLECTION", "Home Collection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("collection_address", models.TextField(blank=True)),
                (
                    "report",
                    models.FileField(blank=True, null=True, upload_to="lab_reports/"),
                ),
                ("report_upload_date", models.DateTimeField(blank=True, null=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "report_signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="users.labtestprescription",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="labtest",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="users.labtestprescription",
            ),
        ),
    ]
