# Generated by Django 5.1.3 on 2025-01-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_staff_is_active_clinic_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="allergies",
            field=models.TextField(blank=True, help_text="List any known allergies"),
        ),
        migrations.AddField(
            model_name="patient",
            name="current_medications",
            field=models.TextField(
                blank=True, help_text="List any current medications"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="existing_diseases",
            field=models.TextField(
                blank=True, help_text="List any existing medical conditions"
            ),
        ),
    ]
