# Generated by Django 5.1.3 on 2025-04-15 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_remove_user_groups_remove_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtest",
            name="doctor_analysis",
            field=models.TextField(
                blank=True, help_text="Doctor's analysis of the test results", null=True
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionitem",
            name="dosage",
            field=models.CharField(
                choices=[
                    ("1-0-0", "Once daily (Morning)"),
                    ("0-1-0", "Once daily (Afternoon)"),
                    ("0-0-1", "Once daily (Night)"),
                    ("1-1-0", "Twice daily (Morning-Afternoon)"),
                    ("1-0-1", "Twice daily (Morning-Night)"),
                    ("0-1-1", "Twice daily (Afternoon-Night)"),
                    ("1-1-1", "Thrice daily"),
                    ("SOS", "As needed (SOS)"),
                ],
                default="1-1-1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionitem",
            name="duration",
            field=models.IntegerField(
                help_text="Duration value (e.g., 7)",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionitem",
            name="duration_unit",
            field=models.CharField(
                choices=[
                    ("days", "Days"),
                    ("weeks", "Weeks"),
                    ("months", "Months"),
                    ("years", "Years"),
                    ("ongoing", "Ongoing"),
                ],
                default="days",
                max_length=10,
            ),
        ),
    ]
