# Generated by Django 5.1.3 on 2025-05-04 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20250504_2025"),
        ("users", "0021_add_missing_fields_to_labtest"),
    ]

    operations = []
