# Generated by Django 5.1.3 on 2025-05-05 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_fix_bill_appointment_field"),
        ("users", "0022_merge_20250504_2027"),
    ]

    operations = []
