# Generated by Django 5.1.3 on 2025-01-06 13:52
from django.db import migrations

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('users', 'UserProfile')
    
    for user in User.objects.all():
        UserProfile.objects.get_or_create(
            user=user,
            defaults={
                'phone_number': '+1234567890',  # Default phone number
            }
        )

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_activitylog_options_and_more'),  # Using the migration we can see in your files
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_func),
    ]