# Generated by Django 5.1.3 on 2025-05-05 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0004_externallabtestoffering"),
        ("users", "0023_merge_20250505_1629"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labtest",
            name="collection_date",
        ),
        migrations.RemoveField(
            model_name="labtest",
            name="doctor_analysis",
        ),
        migrations.AlterField(
            model_name="bill",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bill",
                to="users.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="labtest",
            name="test_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="labs.testdefinition",
            ),
        ),
    ]
