# Generated by Django 5.1.3 on 2025-01-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_create_missing_user_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="date_of_registration",
            field=models.DateField(blank=True, null=True),
        ),
    ]
