# Generated by Django 5.1.3 on 2025-01-12 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_doctor_date_of_registration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["user__first_name", "user__last_name"]},
        ),
        migrations.AddField(
            model_name="patient",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_patients",
                to="users.doctor",
            ),
        ),
    ]
