# Generated by Django 5.1.3 on 2025-05-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_fix_bill_appointment_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("nurse", "Nurse"),
                    ("accountant", "Accountant"),
                    ("receptionist", "Receptionist"),
                    ("lab_technician", "Lab Technician"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
