# Generated by Django 5.1.3 on 2025-05-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_alter_staff_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="appointmentslot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
