# Generated by Django 5.1.3 on 2025-04-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("users", "0019_appointment_fee_appointment_payment_intent_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationbilling",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation_billings",
                to="users.doctor",
            ),
        ),
        migrations.AddField(
            model_name="consultationbilling",
            name="emergency_fee_multiplier",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="consultationbilling",
            name="followup_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="insuranceclaim",
            name="approval_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insuranceclaim",
            name="claim_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Submission"),
                    ("submitted", "Submitted"),
                    ("in_review", "In Review"),
                    ("approved", "Approved"),
                    ("partial", "Partially Approved"),
                    ("rejected", "Rejected"),
                    ("paid", "Paid"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
