# Generated by Django 5.1.3 on 2025-05-17 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_consultationbilling_doctor_and_more"),
        ("billing", "0002_fix_appointment_relationship"),
    ]

    operations = []
