# Generated by Django 5.1.3 on 2025-05-17 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_merge_20250517_1623"),
        ("users", "0027_remove_bill_created_at_remove_bill_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultationbilling",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation_billing",
                to="users.appointment",
            ),
        ),
    ]
