# Generated by Django 5.1.3 on 2025-07-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_fix_consultationbilling_uuid_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partially Paid"),
                    ("paid", "Paid"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
