# Generated by Django 5.1.3 on 2025-07-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_alter_bill_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("debit_card", "Debit Card"),
                    ("credit_card", "Credit Card"),
                    ("upi", "UPI"),
                    ("insurance", "Insurance"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("debit_card", "Debit Card"),
                    ("credit_card", "Credit Card"),
                    ("upi", "UPI"),
                    ("insurance", "Insurance"),
                ],
                max_length=20,
            ),
        ),
    ]
