# Generated by Django 5.1.3 on 2025-07-03 12:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("injection", "Injection"),
                            ("tablet", "Tablet"),
                            ("syrup", "Syrup"),
                            ("topical", "Topical"),
                            ("device", "Medical Device"),
                            ("supplement", "Supplement"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OTC Product",
                "verbose_name_plural": "OTC Products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BillHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=50, unique=True)),
                ("bill_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("finalized", "Finalized"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pharmacy_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_bills",
                        to="users.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
                "ordering": ["-bill_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dispensing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "batch_number_dispensed",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "dispensed_price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_dispensed_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "dispensed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensed_medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispensing",
                "verbose_name_plural": "Dispensings",
                "ordering": ["-dispensed_at"],
            },
        ),
        migrations.CreateModel(
            name="OTCSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "sale_price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("sold_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sold_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="otc_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTC Sale",
                "verbose_name_plural": "OTC Sales",
                "ordering": ["-sold_at"],
            },
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("prescription", "Prescription Drug"),
                            ("otc", "OTC Product"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.billheader",
                    ),
                ),
                (
                    "dispensing",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_item",
                        to="pharmacy.dispensing",
                    ),
                ),
                (
                    "otc_sale",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_item",
                        to="pharmacy.otcsale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill Item",
                "verbose_name_plural": "Bill Items",
                "ordering": ["bill", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Credit/Debit Card"),
                            ("upi", "UPI"),
                            ("netbanking", "Net Banking"),
                            ("insurance", "Insurance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="pharmacy.billheader",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=255)),
                ("website", models.URLField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacies",
                        to="users.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacy",
                "verbose_name_plural": "Pharmacies",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="otcsale",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otc_sales",
                to="pharmacy.pharmacy",
            ),
        ),
        migrations.AddField(
            model_name="dispensing",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispensings",
                to="pharmacy.pharmacy",
            ),
        ),
        migrations.AddField(
            model_name="billheader",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="pharmacy.pharmacy",
            ),
        ),
        migrations.CreateModel(
            name="PharmacyStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("pharmacist", "Pharmacist"),
                            ("assistant", "Pharmacy Assistant"),
                            ("manager", "Pharmacy Manager"),
                            ("intern", "Pharmacy Intern"),
                            ("other", "Other Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_manager", models.BooleanField(default=False)),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="pharmacy.pharmacy",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacy Staff",
                "verbose_name_plural": "Pharmacy Staff",
                "ordering": ["pharmacy", "user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("partially_dispensed", "Partially Dispensed"),
                            ("fully_dispensed", "Fully Dispensed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Date prescription becomes invalid",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_prescriptions",
                        to="users.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_prescriptions",
                        to="users.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="billheader",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="pharmacy.prescription",
            ),
        ),
        migrations.CreateModel(
            name="PrescriptionDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosage_instructions",
                    models.CharField(
                        blank=True,
                        help_text="E.g., '1 tablet twice daily'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration in days (0 for as needed)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_drugs",
                        to="users.drug",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_drugs",
                        to="pharmacy.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription Drug",
                "verbose_name_plural": "Prescription Drugs",
                "ordering": ["prescription", "drug__product_name"],
            },
        ),
        migrations.AddField(
            model_name="dispensing",
            name="prescription_drug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispensings",
                to="pharmacy.prescriptiondrug",
            ),
        ),
        migrations.AddField(
            model_name="otcsale",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="pharmacy.product",
            ),
        ),
        migrations.CreateModel(
            name="StockReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50)),
                ("supplier_name", models.CharField(max_length=255)),
                (
                    "supplier_invoice",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("receipt_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_stock_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_receipts",
                        to="pharmacy.pharmacy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Receipt",
                "verbose_name_plural": "Stock Receipts",
                "ordering": ["-receipt_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date_of_manufacture", models.DateField(blank=True, null=True)),
                ("date_of_expiry", models.DateField()),
                (
                    "purchase_price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_receipt_items",
                        to="users.drug",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.stockreceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Receipt Item",
                "verbose_name_plural": "Stock Receipt Items",
                "ordering": ["receipt", "drug__product_name"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_stock_level",
                    models.PositiveIntegerField(
                        default=10, help_text="Minimum stock level before alert"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_stock",
                        to="users.drug",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="pharmacy.pharmacy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacy Stock",
                "verbose_name_plural": "Pharmacy Stock",
                "ordering": ["pharmacy", "medicine__product_name"],
                "unique_together": {("pharmacy", "medicine", "batch_number")},
            },
        ),
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("min_stock_level", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_stock",
                        to="pharmacy.pharmacy",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="pharmacy.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Stock",
                "verbose_name_plural": "Product Stock",
                "ordering": ["pharmacy", "product__name"],
                "unique_together": {("pharmacy", "product", "batch_number")},
            },
        ),
    ]
