# Generated by Django 5.1.3 on 2025-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="object_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
