# Generated by Django 5.1.3 on 2025-04-09 18:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0014_staff_is_clinic_admin_staff_is_lab_admin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="e.g., 10.00 for 10%",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "platform_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="e.g., 5.00 for 5%",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Commission Rule",
                "verbose_name_plural": "Commission Rules",
            },
        ),
        migrations.CreateModel(
            name="TestDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "short_code",
                    models.CharField(
                        blank=True,
                        help_text="e.g., LOINC code",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("preparation_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Test Definition",
                "verbose_name_plural": "Test Definitions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PATIENT_CHOICE", "Pending Patient Choice"),
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("PENDING_LAB", "Pending Lab Confirmation/Visit"),
                            ("PROCESSING", "Processing at Lab"),
                            ("RESULT_UPLOADED", "Result Uploaded"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING_PATIENT_CHOICE",
                        max_length=30,
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PENDING", "Payment Pending"),
                            ("PAID", "Paid"),
                            ("REFUNDED", "Refunded"),
                            ("FAILED", "Payment Failed"),
                        ],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders",
                        to="users.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="users.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissionLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("doctor_commission", "Doctor Commission"),
                            ("platform_fee", "Platform Fee"),
                        ],
                        default="doctor_commission",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EARNED", "Earned"),
                            ("PENDING_PAYOUT", "Pending Payout"),
                            ("PAID", "Paid"),
                        ],
                        default="EARNED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule_used",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="labs.commissionrule",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_transactions",
                        to="labs.laborder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission Ledger Entry",
                "verbose_name_plural": "Commission Ledger Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Lab's official registration/license number",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Name of the primary contact person", max_length=255
                    ),
                ),
                (
                    "contact_person_designation",
                    models.CharField(
                        help_text="Designation of the contact person", max_length=100
                    ),
                ),
                ("address", models.TextField()),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("accreditation_details", models.TextField(blank=True)),
                (
                    "certifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of standard lab certifications (e.g., ISO, NABL, CAP)",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="lab_logos/"),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Profile",
                "verbose_name_plural": "Lab Profiles",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="laborder",
            name="chosen_lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chosen_orders",
                to="labs.labprofile",
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="doctor_recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommended_orders",
                to="labs.labprofile",
            ),
        ),
        migrations.AddField(
            model_name="commissionrule",
            name="lab",
            field=models.OneToOneField(
                blank=True,
                help_text="Leave blank for global default rule",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="labs.labprofile",
            ),
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True, null=True, upload_to="lab_results/%Y/%m/"
                    ),
                ),
                ("structured_result", models.JSONField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the uploaded file for integrity check",
                        max_length=64,
                    ),
                ),
                (
                    "lab_metadata",
                    models.JSONField(
                        blank=True,
                        help_text="e.g., Lab Name, Technician, Test Method provided at upload",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="labs.laborder",
                    ),
                ),
                (
                    "uploaded_by_lab",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="labs.labprofile",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabOrderTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("status", models.CharField(default="PENDING", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_tests",
                        to="labs.laborder",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="labs.testdefinition",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "test")},
            },
        ),
        migrations.AddField(
            model_name="laborder",
            name="tests",
            field=models.ManyToManyField(
                through="labs.LabOrderTest", to="labs.testdefinition"
            ),
        ),
        migrations.CreateModel(
            name="LabTestOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("turnaround_time_hours", models.IntegerField()),
                ("offers_home_collection", models.BooleanField(default=False)),
                ("specific_instructions", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_offerings",
                        to="users.lab",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_by_labs",
                        to="labs.testdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["test__name"],
                "unique_together": {("lab", "test")},
            },
        ),
    ]
