# Generated by Django 5.1.3 on 2025-07-03 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("labs", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="laborder",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_orders",
                to="users.doctor",
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lab_orders",
                to="users.patient",
            ),
        ),
        migrations.AddField(
            model_name="commissionledger",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commission_transactions",
                to="labs.laborder",
            ),
        ),
        migrations.AddField(
            model_name="labordertest",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_tests",
                to="labs.laborder",
            ),
        ),
        migrations.AddField(
            model_name="labprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="chosen_lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chosen_orders",
                to="labs.labprofile",
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="doctor_recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommended_orders",
                to="labs.labprofile",
            ),
        ),
        migrations.AddField(
            model_name="externallabtestoffering",
            name="lab_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_offerings",
                to="labs.labprofile",
            ),
        ),
        migrations.AddField(
            model_name="commissionrule",
            name="lab",
            field=models.OneToOneField(
                blank=True,
                help_text="Leave blank for global default rule",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="labs.labprofile",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="labs.laborder",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="uploaded_by_lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="labs.labprofile",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="uploaded_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labtestoffering",
            name="lab",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_offerings",
                to="users.lab",
            ),
        ),
        migrations.AddField(
            model_name="labtestoffering",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offered_by_labs",
                to="labs.testdefinition",
            ),
        ),
        migrations.AddField(
            model_name="labordertest",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="labs.testdefinition"
            ),
        ),
        migrations.AddField(
            model_name="laborder",
            name="tests",
            field=models.ManyToManyField(
                through="labs.LabOrderTest", to="labs.testdefinition"
            ),
        ),
        migrations.AddField(
            model_name="externallabtestoffering",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offered_by_external_labs",
                to="labs.testdefinition",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="labtestoffering",
            unique_together={("lab", "test")},
        ),
        migrations.AlterUniqueTogether(
            name="labordertest",
            unique_together={("order", "test")},
        ),
        migrations.AlterUniqueTogether(
            name="externallabtestoffering",
            unique_together={("lab_profile", "test")},
        ),
    ]
