# Generated by Django 5.1.3 on 2025-04-09 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtestoffering",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="labtestoffering",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
