# Generated by Django 5.1.3 on 2025-07-10 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="B2BPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("REFERENCE_LAB", "Reference Lab"),
                            ("HOSPITAL", "Hospital"),
                            ("CLINIC", "Clinic"),
                            ("INSURANCE", "Insurance Company"),
                            ("CORPORATE", "Corporate Client"),
                            ("PHARMACY", "Pharmacy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("tax_id", models.CharField(blank=True, max_length=50)),
                (
                    "credit_days",
                    models.IntegerField(default=30, help_text="Payment terms in days"),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="B2BInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lab_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2b_invoices",
                        to="labs.labprofile",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="labs.b2bpartner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="B2BInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="labs.b2binvoice",
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2b_invoice_items",
                        to="labs.laborder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("ORDER_CONFIRMATION", "Order Confirmation"),
                            ("PAYMENT_REMINDER", "Payment Reminder"),
                            ("COLLECTION_REMINDER", "Collection Reminder"),
                            ("RESULT_READY", "Result Ready"),
                            ("CRITICAL_VALUE", "Critical Value Alert"),
                            ("REPORT_DELIVERY", "Report Delivery"),
                            ("GENERAL", "General Communication"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("FAX", "Fax"),
                            ("PORTAL", "Patient Portal"),
                            ("IN_PERSON", "In Person"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("READ", "Read"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lab_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="labs.labprofile",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="labs.laborder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("REVIEWED", "Reviewed"),
                            ("APPROVED", "Approved"),
                            ("RELEASED", "Released to Patient"),
                            ("AMENDED", "Amended"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("clinical_interpretation", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("critical_values", models.JSONField(blank=True, default=list)),
                ("turnaround_time_hours", models.IntegerField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="labs.laborder",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QualityControlTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "qc_type",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal QC"),
                            ("EXTERNAL", "External QC"),
                            ("PROFICIENCY", "Proficiency Testing"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="e.g., Daily, Weekly, Monthly", max_length=50
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "acceptable_range_min",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "acceptable_range_max",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "westgard_rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Westgard rules to apply",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "test_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_tests",
                        to="labs.testdefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("PATIENT", "Patient"),
                            ("DOCTOR", "Doctor"),
                            ("REFERRING_LAB", "Referring Lab"),
                            ("INSURANCE", "Insurance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("FAX", "Fax"),
                            ("PORTAL", "Patient Portal"),
                            ("IN_PERSON", "In Person"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("READ", "Read"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="labs.labreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specimen_id",
                    models.CharField(
                        help_text="Unique specimen identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "specimen_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood"),
                            ("URINE", "Urine"),
                            ("STOOL", "Stool"),
                            ("SWAB", "Swab"),
                            ("TISSUE", "Tissue"),
                            ("CSF", "Cerebrospinal Fluid"),
                            ("SALIVA", "Saliva"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "collection_method",
                    models.CharField(
                        choices=[
                            ("VENIPUNCTURE", "Venipuncture"),
                            ("FINGER_STICK", "Finger Stick"),
                            ("HEEL_STICK", "Heel Stick"),
                            ("MIDSTREAM", "Midstream Urine"),
                            ("RANDOM", "Random Urine"),
                            ("SWAB", "Swab Collection"),
                            ("BIOPSY", "Biopsy"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("collection_date", models.DateTimeField()),
                ("collection_notes", models.TextField(blank=True)),
                (
                    "volume_ml",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                ("appearance", models.CharField(blank=True, max_length=100)),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, help_text="Batch for processing", max_length=50
                    ),
                ),
                (
                    "processing_priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "Stat"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_specimens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimens",
                        to="labs.laborder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QCResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_value", models.DecimalField(decimal_places=4, max_digits=10)),
                ("run_date", models.DateTimeField()),
                ("instrument", models.CharField(blank=True, max_length=100)),
                ("lot_number", models.CharField(blank=True, max_length=50)),
                ("is_in_control", models.BooleanField()),
                ("westgard_violations", models.JSONField(blank=True, default=list)),
                ("corrective_action", models.TextField(blank=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_qc_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qc_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="labs.qualitycontroltest",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_results",
                        to="labs.specimen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecimenContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        help_text="Unique barcode for specimen identification",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "container_type",
                    models.CharField(
                        choices=[
                            ("VACUTAINER_RED", "BD Vacutainer Red Top"),
                            ("VACUTAINER_PURPLE", "BD Vacutainer Purple Top"),
                            ("VACUTAINER_BLUE", "BD Vacutainer Blue Top"),
                            ("VACUTAINER_GREEN", "BD Vacutainer Green Top"),
                            ("URINE_CONTAINER", "Urine Collection Container"),
                            ("STOOL_CONTAINER", "Stool Collection Container"),
                            ("SWAB_CONTAINER", "Swab Container"),
                            ("CUSTOM", "Custom Container"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lab_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimen_containers",
                        to="labs.labprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="specimen",
            name="container",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specimens",
                to="labs.specimencontainer",
            ),
        ),
        migrations.CreateModel(
            name="SpecimenProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at_lab", models.DateTimeField(blank=True, null=True)),
                ("processing_started", models.DateTimeField(blank=True, null=True)),
                ("processing_completed", models.DateTimeField(blank=True, null=True)),
                ("processing_notes", models.TextField(blank=True)),
                ("quality_check_passed", models.BooleanField(blank=True, null=True)),
                ("quality_check_notes", models.TextField(blank=True)),
                ("storage_location", models.CharField(blank=True, max_length=100)),
                ("disposal_date", models.DateField(blank=True, null=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_specimens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_specimens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specimen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing",
                        to="labs.specimen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_value", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("reference_range", models.CharField(blank=True, max_length=100)),
                ("is_abnormal", models.BooleanField(default=False)),
                (
                    "abnormality_type",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("LOW", "Low"),
                            ("CRITICAL_HIGH", "Critical High"),
                            ("CRITICAL_LOW", "Critical Low"),
                            ("NORMAL", "Normal"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("performed_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="labs.labreport",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="labs.specimen",
                    ),
                ),
                (
                    "test_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labs.testdefinition",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_orders", models.IntegerField(default=0)),
                ("completed_orders", models.IntegerField(default=0)),
                ("pending_orders", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "average_turnaround_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("quality_control_passed", models.IntegerField(default=0)),
                ("quality_control_failed", models.IntegerField(default=0)),
                ("critical_values_count", models.IntegerField(default=0)),
                ("home_collections", models.IntegerField(default=0)),
                ("lab_visits", models.IntegerField(default=0)),
                (
                    "lab_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="labs.labprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("lab_profile", "date")},
            },
        ),
    ]
