# Generated by Django 5.1.3 on 2025-04-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0002_labtestoffering_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labprofile",
            name="lab_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
