# Generated by Django 5.1.3 on 2025-04-11 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0003_labprofile_lab_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalLabTestOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("turnaround_time_hours", models.IntegerField()),
                ("offers_home_collection", models.BooleanField(default=False)),
                ("specific_instructions", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lab_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_offerings",
                        to="labs.labprofile",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_by_external_labs",
                        to="labs.testdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["test__name"],
                "unique_together": {("lab_profile", "test")},
            },
        ),
    ]
