"""
Django settings for RxBackend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import firebase_admin
from firebase_admin import credentials, firestore
import json
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.append(os.path.join(BASE_DIR, 'users', 'scripts'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Load environment variables from .env file
load_dotenv()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', "django-insecure-k8vyukz!b&*so)!y^-(q7_p^3@z98cs598n40+2$iirmreujg5")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'users',
    'social_django',
    'labs',
    'HealthRecords',
    'widget_tweaks',
    'notifications',
    'billing',
    'django.contrib.humanize',
    'pharmacy',
    'appointment',
    'scheduling',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.RoleBasedRedirectionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = "RxBackend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, 'users/templates'),
            # ... other template directories ...
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'users.context_processors.doctor_info',
            ],
        },
    },
]

WSGI_APPLICATION = "RxBackend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    #"default": {
    #    "ENGINE": "django.db.backends.sqlite3",
    #    "NAME": BASE_DIR / "db.sqlite3",
    #}
    #"default": {
    #    "ENGINE": "django.db.backends.postgresql",
    #    "NAME": "rxdoctor",
    #    "USER": "postgres",
    #    "PASSWORD": "admin",
    #    "HOST": "localhost",
    #    "PORT": "5432",
    #}
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'rxdoctor'),
        'USER': os.getenv('DB_USER', 'avnadmin'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'AVNS_j2JJoOD4YoWw-aIRhpW'),
        'HOST': os.getenv('DB_HOST', 'pg-f3d30b1-rxdoctor.g.aivencloud.com'),
        'PORT': os.getenv('DB_PORT', '15132'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}
CORS_ALLOW_ALL_ORIGINS = False  # Set this to False for security
ALLOWED_HOSTS = ['*']  # For development only
CORS_ALLOW_CREDENTIALS = True

# For production, specify allowed origins:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React Native web
    "http://10.0.2.2:3000",   # Android Emulator
    "http://192.168.56.1:3000",
     "http://localhost:8081", # Your local IP for physical devices
]

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Add specific path for clinic logos
CLINIC_LOGOS_URL = '/media/clinic_logos/'
CLINIC_LOGOS_ROOT = os.path.join(MEDIA_ROOT, 'clinic_logos')

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),  # Token expires after 60 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh token expires after 7 days
    'ROTATE_REFRESH_TOKENS': True,                   # Get new refresh token when refreshing access token
    'BLACKLIST_AFTER_ROTATION': True,               # Blacklist old refresh tokens
    'UPDATE_LAST_LOGIN': True,                      # Update last login timestamp
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

CSRF_COOKIE_SAMESITE = 'Lax'  # or 'None' for cross-origin requests
SESSION_COOKIE_SAMESITE = 'Lax'  # or 'None' for cross-origin requests

# Security Settings
SECURE_SSL_REDIRECT = False  # Set to True in production
SESSION_COOKIE_SECURE = False  # Set to True in production
CSRF_COOKIE_SECURE = False  # Set to True in production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# For development, allow HTTP
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8081",
    "http://10.0.2.2:8081",
    "http://192.168.29.57:8000",
    "http://192.168.56.1:19006",
    "http://192.168.56.1:8000",
]
FIREBASE_CONFIG = {
    "apiKey": os.getenv('FIREBASE_API_KEY', "AIzaSyCGnoREZ7l7AYrELWhwKIN7stp9qKoBI4M"),
    "authDomain": os.getenv('FIREBASE_AUTH_DOMAIN', "rxdoctor-d25c3.firebaseapp.com"),
    "projectId": os.getenv('FIREBASE_PROJECT_ID', "rxdoctor-d25c3"),
    "storageBucket": os.getenv('FIREBASE_STORAGE_BUCKET', "rxdoctor-d25c3.firebasestorage.app"),
    "messagingSenderId": os.getenv('FIREBASE_MESSAGING_SENDER_ID', "708530042351"),
    "appId": os.getenv('FIREBASE_APP_ID', "1:708530042351:web:dce2f4264333d6bd5cb21a"),
    "measurementId": os.getenv('FIREBASE_MEASUREMENT_ID', "G-N03MD3X36N")
}

# Add authentication backends
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
)

# Add social auth settings
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_OAUTH2_KEY', 'your-google-oauth2-key')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_OAUTH2_SECRET', 'your-google-oauth2-secret')

# Add your domain to allowed hosts
ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1', '192.168.29.57']

# Login URL configuration
LOGIN_URL = 'users:login'  # This matches your login URL pattern
LOGIN_REDIRECT_URL = 'users:dashboard'  # Where to redirect after successful login
LOGOUT_REDIRECT_URL = 'users:login'  # Where to redirect after logout

# User Model - Using Django's built-in User model
# AUTH_USER_MODEL = 'auth.User'  # This is the default, so we can comment it out

# Migration Safety Settings
MIGRATION_MODULES = {
    # Prevent dangerous migrations in these apps
    'HealthRecords': 'HealthRecords.migrations',
    'users': 'users.migrations', 
    'scheduling': 'scheduling.migrations',
}

# Custom setting to prevent dangerous User model operations
PREVENT_USER_MODEL_MIGRATIONS = True

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development
DEFAULT_FROM_EMAIL = 'noreply@rxdoctor.com'
ADMIN_EMAIL = 'admin@rxdoctor.com'  # Add this line for lab registration notifications